environment:
  global:
    - RANDOM_SEED: 0
  matrix:
    - PYTHON: 3.7

cache:
  - .venv
  - pip

install:
  - choco install make
  - choco install python --version %PYTHON%
  - set PATH=%PATH%;C:\Program Files (x86)\GNU\Make;C:\Python%PYTHON%\Scripts
  - pip install pipenv
  - make doctor
  - make install

build:
  off

test_script:
  - make check
  - make test
